version: '3.6'
networks:
  spam_network:
    name: spam_network
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: spam
#      MONGO_INITDB_ROOT_PASSWORD: shoot4themoon
    networks:
      - spam_network
    volumes:
      - ./mongo-volume:/data/db
